package nsu.titov.ledcontroller.domain.edit.effects

import androidx.compose.ui.graphics.Color
import nsu.titov.ledcontroller.domain.model.canvas.PixelatedCanvas

object PracticalFontTextMapper {

    private val symbolsMap: Map<Char, PixelatedCanvas> by lazy { generateMap() }

    private fun generateMap(): Map<Char, PixelatedCanvas> {
        val map = HashMap<Char, PixelatedCanvas>()

        map[' '] = PixelatedCanvas.withSize(5, 7)

        map['!'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 6] = Color.Red
        }
        map['"'] = PixelatedCanvas.withSize(3, 7).apply {
            this[0, 0] = Color.Red
            this[2, 0] = Color.Red
            this[0, 1] = Color.Red
            this[2, 1] = Color.Red
            this[0, 2] = Color.Red
            this[2, 2] = Color.Red
        }
        map['#'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 1] = Color.Red
            this[3, 1] = Color.Red
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[1, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
            this[1, 5] = Color.Red
            this[3, 5] = Color.Red
        }
        map['$'] = PixelatedCanvas.withSize(5, 7).apply {
            this[2, 0] = Color.Red
            this[1, 1] = Color.Red
            this[2, 1] = Color.Red
            this[3, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[2, 2] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[2, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 5] = Color.Red
            this[2, 5] = Color.Red
            this[3, 5] = Color.Red
            this[2, 6] = Color.Red
        }
        map['%'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[1, 1] = Color.Red
            this[4, 1] = Color.Red
            this[3, 2] = Color.Red
            this[2, 3] = Color.Red
            this[1, 4] = Color.Red
            this[0, 5] = Color.Red
            this[3, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['&'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[0, 1] = Color.Red
            this[3, 1] = Color.Red
            this[0, 2] = Color.Red
            this[3, 2] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[0, 4] = Color.Red
            this[2, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[3, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['\''] = PixelatedCanvas.withSize(1, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
        }
        map['('] = PixelatedCanvas.withSize(2, 7).apply {
            this[1, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 6] = Color.Red
        }
        map[')'] = PixelatedCanvas.withSize(2, 7).apply {
            this[0, 0] = Color.Red
            this[1, 1] = Color.Red
            this[1, 2] = Color.Red
            this[1, 3] = Color.Red
            this[1, 4] = Color.Red
            this[1, 5] = Color.Red
            this[0, 6] = Color.Red
        }
        map['*'] = PixelatedCanvas.withSize(3, 7).apply {
            this[1, 0] = Color.Red
            this[0, 1] = Color.Red
            this[2, 1] = Color.Red
            this[1, 2] = Color.Red
        }
        map['+'] = PixelatedCanvas.withSize(5, 7).apply {
            this[2, 1] = Color.Red
            this[2, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[4, 3] = Color.Red
            this[2, 4] = Color.Red
            this[2, 5] = Color.Red
        }
        map[','] = PixelatedCanvas.withSize(2, 7).apply {
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 5] = Color.Red
            this[1, 6] = Color.Red
        }
        map['-'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[4, 3] = Color.Red
        }
        map['.'] = PixelatedCanvas.withSize(2, 7).apply {
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 5] = Color.Red
        }
        map['/'] = PixelatedCanvas.withSize(3, 7).apply {
            this[2, 0] = Color.Red
            this[2, 1] = Color.Red
            this[1, 2] = Color.Red
            this[1, 3] = Color.Red
            this[1, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
        }
        map['0'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[2, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[2, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[2, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['1'] = PixelatedCanvas.withSize(2, 7).apply {
            this[1, 0] = Color.Red
            this[0, 1] = Color.Red
            this[1, 1] = Color.Red
            this[1, 2] = Color.Red
            this[1, 3] = Color.Red
            this[1, 4] = Color.Red
            this[1, 5] = Color.Red
            this[1, 6] = Color.Red
        }
        map['2'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[3, 3] = Color.Red
            this[2, 4] = Color.Red
            this[1, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['3'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[4, 0] = Color.Red
            this[3, 1] = Color.Red
            this[2, 2] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['4'] = PixelatedCanvas.withSize(5, 7).apply {
            this[3, 0] = Color.Red
            this[1, 1] = Color.Red
            this[3, 1] = Color.Red
            this[1, 2] = Color.Red
            this[3, 2] = Color.Red
            this[0, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
            this[3, 5] = Color.Red
            this[3, 6] = Color.Red
        }
        map['5'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[4, 4] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['6'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['7'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[4, 0] = Color.Red
            this[4, 1] = Color.Red
            this[3, 2] = Color.Red
            this[3, 3] = Color.Red
            this[2, 4] = Color.Red
            this[2, 5] = Color.Red
            this[2, 6] = Color.Red
        }
        map['8'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['9'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[4, 3] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map[':'] = PixelatedCanvas.withSize(2, 7).apply {
            this[0, 1] = Color.Red
            this[1, 1] = Color.Red
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 5] = Color.Red
        }
        map[';'] = PixelatedCanvas.withSize(2, 7).apply {
            this[0, 1] = Color.Red
            this[1, 1] = Color.Red
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 5] = Color.Red
            this[1, 6] = Color.Red
        }
        map['<'] = PixelatedCanvas.withSize(5, 7).apply {
            this[3, 1] = Color.Red
            this[4, 1] = Color.Red
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 5] = Color.Red
            this[4, 5] = Color.Red
        }
        map['='] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
        }
        map['>'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 1] = Color.Red
            this[1, 1] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 3] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 5] = Color.Red
        }
        map['?'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[4, 2] = Color.Red
            this[3, 3] = Color.Red
            this[2, 4] = Color.Red
            this[2, 6] = Color.Red
        }
        map['@'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[2, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['A'] = PixelatedCanvas.withSize(5, 7).apply {
            this[2, 0] = Color.Red
            this[1, 1] = Color.Red
            this[3, 1] = Color.Red
            this[1, 2] = Color.Red
            this[3, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['B'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['C'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['D'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['E'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['F'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
        }
        map['G'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[3, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['H'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['I'] = PixelatedCanvas.withSize(1, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
        }
        map['J'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[4, 0] = Color.Red
            this[4, 1] = Color.Red
            this[4, 2] = Color.Red
            this[4, 3] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['K'] = PixelatedCanvas.withSize(5, 7).apply {

        }
        map['L'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['M'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[1, 1] = Color.Red
            this[3, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[2, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[2, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['N'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[1, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[2, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[3, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['O'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['P'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
        }
        map['Q'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[2, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[3, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['R'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[2, 4] = Color.Red
            this[0, 5] = Color.Red
            this[3, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['S'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['T'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[4, 0] = Color.Red
            this[2, 1] = Color.Red
            this[2, 2] = Color.Red
            this[2, 3] = Color.Red
            this[2, 4] = Color.Red
            this[2, 5] = Color.Red
            this[2, 6] = Color.Red
        }
        map['U'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['V'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[1, 4] = Color.Red
            this[3, 4] = Color.Red
            this[1, 5] = Color.Red
            this[3, 5] = Color.Red
            this[2, 6] = Color.Red
        }
        map['W'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[0, 2] = Color.Red
            this[2, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[2, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[2, 4] = Color.Red
            this[4, 4] = Color.Red
            this[1, 5] = Color.Red
            this[3, 5] = Color.Red
            this[1, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['X'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[1, 2] = Color.Red
            this[3, 2] = Color.Red
            this[2, 3] = Color.Red
            this[1, 4] = Color.Red
            this[3, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['Y'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[4, 0] = Color.Red
            this[0, 1] = Color.Red
            this[4, 1] = Color.Red
            this[1, 2] = Color.Red
            this[3, 2] = Color.Red
            this[2, 3] = Color.Red
            this[2, 4] = Color.Red
            this[2, 5] = Color.Red
            this[2, 6] = Color.Red
        }
        map['Z'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[4, 0] = Color.Red
            this[4, 1] = Color.Red
            this[3, 2] = Color.Red
            this[2, 3] = Color.Red
            this[1, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['['] = PixelatedCanvas.withSize(2, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
        }
        map['\\'] = PixelatedCanvas.withSize(3, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[1, 2] = Color.Red
            this[1, 3] = Color.Red
            this[1, 4] = Color.Red
            this[2, 5] = Color.Red
            this[2, 6] = Color.Red
        }
        map[']'] = PixelatedCanvas.withSize(2, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[1, 1] = Color.Red
            this[1, 2] = Color.Red
            this[1, 3] = Color.Red
            this[1, 4] = Color.Red
            this[1, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
        }
        map['^'] = PixelatedCanvas.withSize(5, 7).apply {
            this[2, 0] = Color.Red
            this[1, 1] = Color.Red
            this[3, 1] = Color.Red
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
        }
        map['_'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['`'] = PixelatedCanvas.withSize(3, 7).apply {
            this[0, 0] = Color.Red
            this[1, 1] = Color.Red
            this[2, 2] = Color.Red
        }
        map['a'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 3] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['b'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['c'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['d'] = PixelatedCanvas.withSize(5, 7).apply {
            this[4, 0] = Color.Red
            this[4, 1] = Color.Red
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['e'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['f'] = PixelatedCanvas.withSize(4, 7).apply {
            this[2, 0] = Color.Red
            this[3, 0] = Color.Red
            this[1, 1] = Color.Red
            this[1, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[1, 4] = Color.Red
            this[1, 5] = Color.Red
            this[1, 6] = Color.Red
        }
        map['g'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['h'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[3, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['i'] = PixelatedCanvas.withSize(1, 7).apply {
            this[0, 0] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
        }
        map['j'] = PixelatedCanvas.withSize(2, 7).apply {
            this[1, 0] = Color.Red
            this[1, 2] = Color.Red
            this[1, 3] = Color.Red
            this[1, 4] = Color.Red
            this[1, 5] = Color.Red
            this[0, 6] = Color.Red
        }
        map['k'] = PixelatedCanvas.withSize(4, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[3, 2] = Color.Red
            this[0, 3] = Color.Red
            this[2, 3] = Color.Red
            this[0, 4] = Color.Red
            this[1, 4] = Color.Red
            this[0, 5] = Color.Red
            this[2, 5] = Color.Red
            this[0, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['l'] = PixelatedCanvas.withSize(2, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[1, 6] = Color.Red
        }
        map['m'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[3, 2] = Color.Red
            this[0, 3] = Color.Red
            this[2, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[2, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[2, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[2, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['n'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['o'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['p'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[1, 3] = Color.Red
            this[4, 3] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[1, 5] = Color.Red
            this[1, 6] = Color.Red
        }
        map['q'] = PixelatedCanvas.withSize(5, 7).apply {
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[1, 3] = Color.Red
            this[4, 3] = Color.Red
            this[1, 4] = Color.Red
            this[4, 4] = Color.Red
            this[2, 5] = Color.Red
            this[3, 5] = Color.Red
            this[4, 5] = Color.Red
            this[4, 6] = Color.Red
        }
        map['r'] = PixelatedCanvas.withSize(4, 7).apply {
            this[0, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
        }
        map['s'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['t'] = PixelatedCanvas.withSize(4, 7).apply {
            this[1, 0] = Color.Red
            this[1, 1] = Color.Red
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[1, 3] = Color.Red
            this[1, 4] = Color.Red
            this[1, 5] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['u'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[0, 5] = Color.Red
            this[3, 5] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['v'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[4, 4] = Color.Red
            this[1, 5] = Color.Red
            this[3, 5] = Color.Red
            this[2, 6] = Color.Red
        }
        map['w'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[0, 3] = Color.Red
            this[2, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[2, 4] = Color.Red
            this[4, 4] = Color.Red
            this[1, 5] = Color.Red
            this[3, 5] = Color.Red
            this[1, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['x'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[1, 3] = Color.Red
            this[3, 3] = Color.Red
            this[2, 4] = Color.Red
            this[1, 5] = Color.Red
            this[3, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['y'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 2] = Color.Red
            this[4, 2] = Color.Red
            this[1, 3] = Color.Red
            this[4, 3] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
            this[4, 4] = Color.Red
            this[4, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
        }
        map['z'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 2] = Color.Red
            this[1, 2] = Color.Red
            this[2, 2] = Color.Red
            this[3, 2] = Color.Red
            this[4, 2] = Color.Red
            this[3, 3] = Color.Red
            this[2, 4] = Color.Red
            this[1, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
            this[3, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['x'] = PixelatedCanvas.withSize(5, 7).apply {
            this[0, 2] = Color.Red
            this[4, 2] = Color.Red
            this[1, 3] = Color.Red
            this[3, 3] = Color.Red
            this[2, 4] = Color.Red
            this[1, 5] = Color.Red
            this[3, 5] = Color.Red
            this[0, 6] = Color.Red
            this[4, 6] = Color.Red
        }
        map['{'] = PixelatedCanvas.withSize(3, 7).apply {
            this[1, 0] = Color.Red
            this[2, 0] = Color.Red
            this[1, 1] = Color.Red
            this[1, 2] = Color.Red
            this[0, 3] = Color.Red
            this[1, 4] = Color.Red
            this[1, 5] = Color.Red
            this[1, 6] = Color.Red
            this[2, 6] = Color.Red
        }
        map['|'] = PixelatedCanvas.withSize(1, 7).apply {
            this[0, 0] = Color.Red
            this[0, 1] = Color.Red
            this[0, 2] = Color.Red
            this[0, 3] = Color.Red
            this[0, 4] = Color.Red
            this[0, 5] = Color.Red
            this[0, 6] = Color.Red
        }
        map['}'] = PixelatedCanvas.withSize(3, 7).apply {
            this[0, 0] = Color.Red
            this[1, 0] = Color.Red
            this[1, 1] = Color.Red
            this[1, 2] = Color.Red
            this[2, 3] = Color.Red
            this[1, 4] = Color.Red
            this[1, 5] = Color.Red
            this[0, 6] = Color.Red
            this[1, 6] = Color.Red
        }
        map['~'] = PixelatedCanvas.withSize(5, 7).apply {
            this[1, 3] = Color.Red
            this[2, 3] = Color.Red
            this[4, 3] = Color.Red
            this[0, 4] = Color.Red
            this[2, 4] = Color.Red
            this[3, 4] = Color.Red
        }
        return map
    }

    val UnknownSymbol = PixelatedCanvas(5, 7, Array(5 * 7) { Color.Red })

    fun map(symbol: Char): PixelatedCanvas = symbolsMap[symbol] ?: UnknownSymbol
}